FROM debian:12

RUN apt-get update && \
    apt-get install -y debmirror gnupg curl rsync debian-archive-keyring && \
    apt-get clean

COPY sync-debian-security.sh /usr/local/bin/sync-debian-security.sh
RUN chmod +x /usr/local/bin/sync-debian-security.sh

ENTRYPOINT ["/usr/local/bin/sync-debian-security.sh"]