FROM debian:10

RUN apt-get update && \
    apt-get install -y debmirror gnupg curl rsync debian-archive-keyring && \
    apt-get clean

COPY sync-debian-mirror.sh /usr/local/bin/sync-debian-mirror.sh
RUN chmod +x /usr/local/bin/sync-debian-mirror.sh

ENTRYPOINT ["/usr/local/bin/sync-debian-mirror.sh"]
